<%
dim conStr
conStr="Provider=SQLOLEDB;Server=tcp:crschecks2.database.windows.net,1433;Database=accessweb;User ID=accessweb;Password=Cubic9004sl;Encrypt=True;Trusted_Connection=False;"

'Constr="Server=tcp:crschecks.database.windows.net,1433;Initial Catalog=accessweb;Persist Security Info=False;User ID=accessweb;Password=Cubic9004sl;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

%>
